### GET request with a header
PUT http://localhost:8080/stash/100
Accept: text/plain

Value for
key 100

> {%
client.test("control_01", function() {
  client.assert(response.status === 201, "Response status is not 201");
})
 %}

###
PUT http://localhost:8080/stash/200
Accept: text/plain

Value for Значение
key 200 ключ 200


> {%
client.test("control_01", function() {
  client.assert(response.status === 201, "Response status is not 201");
})
 %}

### Put and get test
PUT http://localhost:8080/stash/control_01
Accept: text/plain

Value for control_01

###
GET http://localhost:8080/stash/control_01
Accept: text/plain

> {%
client.test("control_01", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.body === "Value for control_01")
})
 %}