### GET request with a header
PUT http://localhost:8080/s/my_first_db/100
Accept: text/plain

Value for
key 100

> {%
client.test("key 100", function() {
  client.assert(response.status === 201, "Response status is not 201");
})
 %}

###
PUT http://localhost:8080/s/my_first_db/200
Accept: text/plain

Value for Значение
key 200 ключ 200


> {%
client.test("key 200", function() {
  client.assert(response.status === 201, "Response status is not 201");
})
 %}

### Put and get test
PUT http://localhost:8080/s/my_first_db/control_01
Accept: text/plain

Value for control_01

###
GET http://localhost:8080/s/my_first_db/control_01
Accept: text/plain

> {%
client.test("key control_01", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.body === "Value for control_01")
})
 %}


###
GET http://localhost:8080/s/one.json/control_01
Accept: text/plain

> {%
client.test("key control_01", function() {
  client.assert(response.status === 404, "Response status is not 200");
})
 %}


### GET request with a header
GET http://localhost:8080/s/my_first_db
Accept: text/plain

> {%
client.test("key 100", function() {
  client.assert(response.status === 200, "Response status is not 200");
})
 %}


### DELETE
DELETE http://localhost:8080/s/my_first_db
Accept: text/plain

> {%
client.test("key 100", function() {
  client.assert(response.status === 200, "Response status is not 200");
})
 %}
